<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>CleanArchitecture.OutboxWorker</RootNamespace>
    <AssemblyName>CleanArchitecture.OutboxWorker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
