<!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
<Project>
  <Import Project="$(MSBuildThisFileDirectory)build\ClientFramework.props" Condition="Exists('$(MSBuildThisFileDirectory)build\ClientFramework.props')" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Suppress NU1608 until Npgsql.EntityFrameworkCore.PostgreSQL 10.0.0 is released -->
    <WarningsNotAsErrors>NU1608</WarningsNotAsErrors>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ClientFramework)' == 'React'">
    <DefineConstants>$(DefineConstants);UseReact</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(ClientFramework)' == 'Angular'">
    <DefineConstants>$(DefineConstants);UseAngular</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(ClientFramework)' == 'ApiOnly'">
    <DefineConstants>$(DefineConstants);UseApiOnly</DefineConstants>
  </PropertyGroup>
</Project>
