# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

# GET Identity Account Login
# Get the @RequestVerificationToken necessary for logging in.
GET {{Web_HostAddress}}/Identity/Account/Login

###

# POST Identity Account Login
# Supply credentials for an existing account. The template does not seed a default administrator.
@Email=<ExistingAccountEmail>
@Password=<ExistingAccountPassword>
@RequestVerificationToken=<RequestVerificationToken>
POST {{Web_HostAddress}}/Identity/Account/Login
Content-Type: application/x-www-form-urlencoded

Input.Email={{Email}}&Input.Password={{Password}}&__RequestVerificationToken={{RequestVerificationToken}}
