<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CleanArchitecture.TestAppHost</RootNamespace>
    <AssemblyName>CleanArchitecture.TestAppHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" Condition="'$(DatabaseProvider)' == 'PostgreSQL'" />
    <PackageReference Include="Aspire.Hosting.Azure.Sql" Condition="'$(DatabaseProvider)' == 'SqlServer'" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SQLite" Condition="'$(DatabaseProvider)' == 'Sqlite'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
